name: flutter_music
description: Music Pomodoro app with player and timer
publish_to: "none"

version: 1.0.0+1 # добавь эту строку для решения предупреждения о версии

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^5.2.1 # добавь эту строку
  # остальные зависимости...

flutter:
  uses-material-design: true
