name: flutter_music
description: Music Pomodoro app with player and timer
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # остальные зависимости, если есть

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
